apiVersion: apps/v1
kind: Deployment
metadata:
  {{- if .Values.environment.testName }}
  name: {{ .Chart.Name }}-{{ .Values.environment.testName | lower  }}
  labels:
    app: {{ .Chart.Name }}-{{ .Values.environment.testName | lower  }}
    chart: {{ .Chart.Name }}-{{ .Values.environment.testName | lower  }}
  {{- else }}
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Name }}
  {{- end }}
spec:
  selector:
    matchLabels:
  {{- if .Values.environment.testName }}
      app: {{ .Chart.Name }}-{{ .Values.environment.testName | lower  }}
  {{- else }}
      app: {{ .Chart.Name }}
  {{- end }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
  {{- if .Values.environment.testName }}
        app: {{ .Chart.Name }}-{{ .Values.environment.testName | lower  }}
  {{- else }}
        app: {{ .Chart.Name }}
  {{- end }}
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: {{ .Chart.Name }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.containerRegistry }}/{{ .Values.image.service }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            requests:
              memory: {{ .Values.resources.requests.memory | quote }}
              cpu: {{ .Values.resources.requests.cpu | quote }}
            limits:
              memory: {{ .Values.resources.limits.memory | quote }}
              cpu: {{ .Values.resources.limits.cpu | quote }}
          env:
          # Pod / Node information
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
      imagePullSecrets:
        - name: registrypullsecret
        {{- if .Values.global.imagePullSecrets }}
        - name: {{ .Values.global.imagePullSecrets }}
        {{- end }}
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution: # prefer to schedule it on user node over system node
            - weight: 100
              preference:
                matchExpressions:
                  - key: kubernetes.azure.com/mode
                    operator: In
                    values:
                      - user
