apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  {{- if .Values.environment.testName }}
  name: {{ .Chart.Name }}-{{ .Values.environment.testName }}
  {{- else }}
  name: {{ .Chart.Name }}
  {{- end }}
  annotations:
    # traefik 1.x
    external-dns.alpha.kubernetes.io/target: gateway.{{ .Values.environment.name | lower }}.{{ .Values.environment.publicDomain }}
    # traefik 2.x
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  {{- if .Values.environment.testName }}
  - host: {{ .Chart.Name }}-{{ .Values.environment.testName | lower }}.{{ .Values.environment.name | lower }}.{{ .Values.environment.publicDomain }}
  {{- else }}
  - host: {{ .Chart.Name }}.{{ .Values.environment.name | default .Values.global.environment.name  | lower }}.{{ .Values.environment.publicDomain | default .Values.global.environment.publicDomain  }}
  {{- end }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
  {{- if .Values.environment.testName }}
            name: {{ .Chart.Name }}-{{ .Values.environment.testName | lower }}
  {{- else }}
            name: {{ .Chart.Name }}
  {{- end }}
            port:
              number: 80        